version: '3.1'

services:

  postgres:
    image: postgres:11.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: flexehr
    ports:
      - '5432:5432'